version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - java -version
      - mvn install
      - mvn -v
      - mvn clean install
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/spring-boot-sample-app-1.0.0.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
