version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - java -version
      - mvn install
      - mvn -v
      - mvn clean install
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/spring-boot-sample-app-1.0.0.jar
    - scripts/server_clear.sh
    - scripts/fix_privileges.sh
    - scripts/server_start.sh
    - scripts/server_stop.sh
    - appspec.yml
